version: "2.1"
services:
  redis-stack-lab:
    image: redis/redis-stack:latest
    container_name: redis-stack-lab
    volumes:
      - ./local-data:/data
    ports:
      - 6379:6379
      - 8001:8001